version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.bun
    container_name: library-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - library-network

networks:
  library-network:
    driver: bridge
